@startuml test04AplicarDescuentoMas40M2
    hide footbox
    skinparam classAttributeIconSize 0
   
    autonumber 1.0
    actor Luis
    activate Luis
    Luis -> ":prueba" as prueba: test04AplicarDescuento
    activate prueba

     autonumber 2.0
    prueba -> prueba: alba = crearPintura(alba, 200, 1, 1)

    create "alba:Pintura" as alba
    prueba -> alba: << create >>
    activate alba
    
    autonumber 3.0
    prueba -> prueba: pintor = registrarPintorDePincel("Diego", 500)

    create "pintor:Pintor" as pintor
    prueba -> pintor: << create >>
    activate pintor

    create "pincel: Pincel" as pincel
    pintor -> pincel: << create >>
    activate pincel

    create "descuento:Descuento" as descuento
    pincel -> descuento: << create >>
    activate descuento


    autonumber 4.0
    prueba -> pintor: calcularCostoM2ConPintura(39, alba)


    pintor -> pintor: costoManoObra = costoManoObra(39)
    pintor -> pintor: costoMateriales = costoMateriales(alba, 39)

    pintor -> pincel: numManos = numeroManos(alba)

    autonumber 4.4.1
    pintor -> pintor: descuento = costoManoObra * descuento()
    pintor -> pincel: descuento(39)
    pincel -> descuento: puedoAplicar()
    descuento --> pincel: false
    pincel -> pincel: descuento = 0
    pincel --> pintor: descuento

    pintor -> pintor
    note right: costoProyecto = (manoObra - descuento + costoMateriales) * numManos


    autonumber 5.0
    prueba -> pintor: presupuesto = valor()
    pintor --> prueba: valor

    autonumber 6.0   
    prueba --> Luis: presupuesto

@enduml